### ISSUE TITLE
[Anon] Bug report: Rebel_Alliance.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/star-wars-armada#13] opened 2015-06-04 21:55 UTC
**File:** Rebel_Alliance.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** The max points available for squadrons should be 1/3 of the max fleet value. Currently it is set at 100 for all fleet point values, thus giving incorrect errors when building a fleet over 300 points or allowing more squadrons than should be allowed when building a fleet under 300 points.

**Comment by BrianisBlack** [comment] 2015-06-06 01:20
This is a duplicate of issue #3. Still waiting for a fix from the battlescribe dev. Until then, it's gotta stay hard coded at the tournament limit, otherwise it some other arbitrary limit.

**Closed by BrianisBlack** 2015-06-06 01:20 UTC
